apiVersion: apps/v1
kind: Deployment
metadata:
  name: deforestation-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: deforestation-api
  template:
    metadata:
      labels:
        app: deforestation-api
    spec:
      containers:
        - image: ghcr.io/openearthplatforminitiative/deforestation-api:0.2.2
          name: deforestation-api
          ports:
            - containerPort: 8080
          env:
            - name: API_ROOT_PATH
              value: "/deforestation"
            - name: VERSION
              value: 0.2.2
            - name: API_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: openepi-apps-config
                  key: api_domain
---
apiVersion: v1
kind: Service
metadata:
  name: deforestation-api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: deforestation-api
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix-deforestation
spec:
  stripPrefix:
    prefixes:
      - /deforestation
    forceSlash: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: deforestation-api
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/deforestation`)
    services:
    - kind: Service
      name: deforestation-api
      port: 80
    middlewares:
    - name: forward-auth-forward-auth@kubernetescrd
    - name: stripprefix-deforestation

